### PR TITLE
closes #298

### LINKED ISSUE #298: Error 404 when call '/' and workflow try to redirect in '/en' with query params
With workflow and using prefixes in the middleware check if you try to get '/' and the workflow redirect you in home (/en for example). The query string param added from facebook, for example fbclid, broken this function and the site return 404 page. This behavior because the function check req.url == '/', and in this case req.url = '/?querystring=queryparam', so the function return next(). For my opinion the condition req.url == '/' should be changed in req.url.split('?')[0] == '/' and add after the query params.

### PR DESCRIPTION
**Pull request by boutell**

### CODE REVIEW

**Comment by boutell** [comment]
closes #298 by ensuring that an access to the root URL (/) is still recognized as such when it has a query string, and preserving that query string when redirecting to the prefix associated with the user's locale. Formerly we already did this but only if it was query string-free.

File: lib/middleware.js [hunk 1]
```diff
@@ -218,9 +218,14 @@ module.exports = function(self, options) {
         }
       }
 
-      if (self.prefixes && self.prefixes[self.liveify(req.locale)] && (req.url === '/')) {
+      if (self.prefixes && self.prefixes[self.liveify(req.locale)] && req.url.match(/^\/(\?|$)/)) {
         // Redirect to home page of appropriate locale
-        return res.redirect(self.prefixes[self.liveify(req.locale)] + '/');
+        let newUrl = self.prefixes[self.liveify(req.locale)] + '/';
+        const matches = req.url.match(/^\/(\?.*)$/);
```
Comment (abea) [inline lib/middleware.js]: This includes the `/`, doesn't it? So you would end up with `new.url//?query=string`.

Comment (boutell) [reply lib/middleware.js]: Nope, not that I can see:

```
const urls = [
  '/', '/foo', '/foo/bar', '/?bar=wizzle'
];

for (const url of urls) {
  if (url.match(/^\/(\?|$)/)) {
    let newUrl = '/prefixed/';
    const matches = url.match(/^\/(\?.*)$/);
    if (matches) {
      newUrl += matches[1];
    }
    console.log(url + ' is now ' + newUrl);
  } else {
    console.log('just ' + url);
  }
}
```

Behaves properly.
